name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      id-token: write
      pages: write
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v7

      # Install dependencies (curl, wget, tar)
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y curl wget tar

      # Download and extract the release
      - name: Download and extract Ketesa
        run: |
          source version.env
          wget https://github.com/etkecc/ketesa/releases/download/${VERSION}/ketesa.tar.gz
          tar zfx ketesa.tar.gz
          mv ketesa public

      - name: Move config.json
        run: |
          mv config.json public

      # Upload the public directory as an artifact
      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v5
        with:
          path: public
      
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v5
    
    #   # Deploy to Cloudflare Pages
    #   - name: Deploy to Cloudflare Pages
    #     uses: cloudflare/pages-action@v1
    #     with:
    #       apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    #       accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    #       projectName: communicate
    #       directory: public